### ISSUE TITLE
"No instance nor default method for class operation <>" error with GHC-8.4.2

### ISSUE THREAD

**Issue by costructuralist** [nikita-volkov/hasql#92]
The following runtime error is produced when executing a `"select ($1 + $2)"` test query:

```
library\Hasql\Private\Commands.hs:21:10-27: No instance nor default method for class operation <>
```

This is using the `nightly-2018-05-30` snapshot on Stackage, which uses GHC-8.4.2 and hasql-1.3.0.1

I'm guessing it's related to [phase 2 of the semigroup-monoid proposal](https://downloads.haskell.org/~ghc/8.4.2/docs/html/users_guide/8.4.1-notes.html#highlights).

**Comment by gcharnock** [comment]
Just got this too. Stackage nightly `nightly-2018-06-02`

**Comment by gcharnock** [comment]
So a workaround for me was to use `lts-11.11` and add hasql and some associated packages as `extra-deps`

```
extra-deps: [ hasql-1.3.0.1, text-builder-0.5.1, hasql-pool-0.5 ]
```

**Comment by nikita-volkov** [comment]
This should be fixed in 1.3.0.2

**Comment by viviag** [comment]
This is still present.
`library/Hasql/Private/Commands.hs:21:10-27: No instance nor default method for class operation <>`
lts-12.8
Explicit bound `>= 1.3.0.2` in `.cabal` file.
